#!/bin/sh

git shortlog -se \
  | perl -spe 's/^\s+\d+\s+//' \
  | sed -e '/^CommitSyncScript.*$/d' \
  > AUTHORS

# This file lists all individuals having contributed content to the repository.
# For how it is generated, communicate with us or check to see `hack/generate-authors.sh`.

James Okonkwo <jamesejike04@gmail.com>
Mary Precious Okorom <maryprecious144@gmail.com>

